### ISSUE TITLE
Installation via rockspec does not work

### ISSUE THREAD

**Issue by mkermani** [Phrogz/SLAXML#14]
Hello,

I was trying to install the package via `luarocks install slaxml-0.7-0.rockspec` and it didn't suceed. 

After some modifications I managed to do it by:
* changing the name to `slaxml-0.8-0.rockspec`, i.e., the name should be exactly `<package_name>-<version>.rockspec`
* changing the url in the `.rockspec` file from "https://github.com/Phrogz/SLAXML.git" to "url = "git://github.com/Phrogz/SLAXML.git"", i.e., replacing `https` with `git`

**Comment by Phrogz** [comment]
I'v uploaded the rockspec now.
https://luarocks.org/modules/phrogz/slaxml
